### ISSUE TITLE
Missing de facto standard format/2-3 predicates

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#128]
Would be possible to add the de facto standard `format/2-3` predicates? Any (relatively) easy way for lifting the required functionality from an existing JS library?

For sample calls and tests, please see:
https://github.com/LogtalkDotOrg/logtalk3/blob/master/tests/prolog/predicates/format_2/tests.lgt
https://github.com/LogtalkDotOrg/logtalk3/blob/master/tests/prolog/predicates/format_3/tests.lgt

**Comment by pmoura** [comment]
Btw, Markus wrote a nice Prolog implementation of the `format/2-3` predicates for Scryer Prolog. If he would be willing to contribute it to Tau-Prolog, it could be an alternative to a native JS implementation.

**Comment by jariazavalverde** [comment]
> Btw, Markus wrote a nice Prolog implementation of the `format/2-3` predicates for Scryer Prolog. If he would be willing to contribute it to Tau-Prolog, it could be an alternative to a native JS implementation.

That sounds really interesting. @triska It would be a great help!

**Comment by triska** [comment]
Thank you very much for your interest! `format.pl` is available from:

https://github.com/mthom/scryer-prolog/blob/master/src/prolog/lib/format.pl

It would be awesome if you could integrate it in Tau Prolog too, this is a great opportunity for collaboration between two Prolog systems that are very conforming to the ISO standard and hence allow easy porting of applications and libraries. It is especially fortunate that both systems have taken the bold step to set `double_quotes` to `chars` by default, a setting which I strongly encourage and which `format.pl` also assumes.

If possible, please make the non-terminal `format_//2` from this library also available in Tau&nbsp;Prolog: I have found `format_//2` to be a really useful building block to format lists of characters, and to declaratively describe output so that it can actually be reasoned about in test cases instead of appearing only on the screen.

The library also provides `listing/1` and `portray_clause/1`, which I hope you also find useful for Tau Prolog. I often use `portray_clause/1` when emitting solutions to generate output that can later be read with `read/1` for convenient testing and reasoning.

Please let me know if you need anything specific to use the library: Ideally, porting it should amount to maybe changing a few directives, and changing the two occurrences of "Scryer" to "Tau".

**Comment by pmoura** [comment]
@triska Looking at the code of `format.pl`, there is `format/2` but not `format/3`. Easy to add, of course. Also, `format/2` only accepts (as first argument) a double-quoted term, correct? Other Prolog system implementations also accept an atom. I can submit a pull request to fix both omissions. But I'm wondering if there's some design decision here.

**Comment by triska** [comment]
Yes, well spotted! In Scryer Prolog, I have consciously chosen *not* to support an atom as the first argument: First, as you say, an atom inflates the atom table, and should be avoided unless one really needs it for indexing. A second reason are security concerns I think about when using atoms: The atoms that occurred while running a program leave more traces in the system state than lists, and one sometimes does not want to leave a trace of what was processed. As a general rule for using atoms vs. strings, I think the more ephemeral the data is used, the better it is to use lists of characters instead of atoms. Since in this case, the format string is only used once, lists are a very good fit, and make it easy to process the argument in the library.

For me, an even better reason to support only double quoted strings is to encourage better support for this feature also in other Prolog systems: There are ways to implement lists of characters very efficiently, they only have not yet caught on. My hope is that over time, we will  eventually be able to use Prolog for the use case it was designed for: Efficient and convenient processing of text. This will only happen with bold steps as the ones taken by Scryer and Tau, by committing to lists of characters once and for all, and then implementing that efficiently. I would like to promote the use of lists of characters for this reason already: To encourage implementors to make this efficient.

**Comment by pmoura** [comment]
Fully agree with your reasoning. In Logtalk, I'm unfortunately forced to use atoms (for now) to avoid portability issues with the (currently) 12 supported Prolog systems (hopefully, soon it will be 14 🙂). I should be able to workaround Tau Prolog and Scryer Prolog not supporting an atom until it's no longer a portability issue. The main problem (in my view) of double-quoted terms is that their interpretation depends on a flag (`double_quotes`). The absence of a string term type independent of any flag is quite unfortunate.

**Comment by jariazavalverde** [comment]
Thank you very much @triska!

I am doing some quick tests (as some of the required predicates are missing in Tau Prolog) and Tau Prolog seems to be working correctly, or at least giving the same results as SWI-Prolog. But I'm a bit lost with what the `format/2` predicate prints.

For example, the goal `format("~ta~t~4|", []).` prints `1261169712611612652124` instead of `a     `. Analogously for other examples of your module. `format("~2f~n", [3]).` even gives me a domain error (in both Tau and SWI).

Is this due to the lack of a specific predicate in Tau Prolog and SWI-Prolog?

![swi](https://user-images.githubusercontent.com/5055295/82105560-46bea880-971c-11ea-82a0-c678cc86028b.png)

![tauformat](https://user-images.githubusercontent.com/5055295/82105563-4d4d2000-971c-11ea-8c52-dc793a75b92c.png)

**Comment by triska** [comment]
`format.pl` requires that `double_quotes` be set to **`chars`**.

I am consciously not supporting `codes`, because I would like to encourage applications programmers and implementors to move towards `chars`. Or rather, to *return* to `chars`, because that is what the very first Prolog implementation already did.

Could you please try it again, with the Prolog flag `double_quotes` set to `chars`?

**Comment by pmoura** [comment]
I have been giving this some thought. In a Prolog system supporting (1) modules and (2) a `double_quotes` flag **local** to modules, having `format/2-3` predicates requiring the flag set to `chars` can work for most cases. You need to call the `format/2-3` predicates from within a module, you simply add a **local** directive:

```prolog
:- set_prolog_flag(double_quotes, chars).
```

Code elsewhere can then use a different setting for the flag without consequences. With the `double_quotes` flag being global, however, an application calling the `format/2-3` predicates **must** set (or can only use) the flag to `chars`. That means that any existing program using a different setting (e.g. `codes`) cannot call the  `format/2-3` predicates until is rewritten. One way out, as I mention earlier, is to support passing an atom in the first argument of the predicates, which makes the calls independent of the `double_quotes` flag setting. The requires change is something like:

```prolog
format(Fs, Args) :-
        atom(Fs),
        !,
        atom_chars(Fs, Chars),
        format(Chars, Args).
format(Fs, Args) :-
        phrase(format_(Fs, Args), Cs),
        maplist(write, Cs).
```

Similar for `format/3`. This could also be extended to check the value of the `double_quotes` flag and make any necessary conversion before calling `phrase/2`.

**Comment by jariazavalverde** [comment]
Okay. It's a problem with my `foldl/4` implementation. The accumulator is on the wrong side! :open_mouth: Now everything seems to be working properly. The rest is a piece of cake, just add a couple of predicates to Tau Prolog. Thank you again!

I publish the Tau Prolog packages as predicates directly compiled into JavaScript, rather than as Prolog text. So if you like, I could add your copyright header in the package next to a link to the original Prolog source.

**Comment by triska** [comment]
> That means that any existing program using a different setting (e.g. codes) cannot call the 
> format/2-3 predicates until is rewritten. 

Yes, exactly: This consideration is the key motivation for this design. I want to encourage application programmers to make one final change to their code: Move from codes to characters. This is the last time they need to do this, since all future Prolog systems will use characters by default. Scryer demonstrates how this can be implemented efficiently, using a compact internal representation.

**Comment by triska** [comment]
@jariazavalverde : Thank you, that would be very generous!

Enjoy!

**Comment by pmoura** [comment]
@triska For portable programs, which must also run on Prolog systems where `chars` is not supported, this would require either going from one version of the program to multiple versions or ditching support for those Prolog systems.

**Comment by triska** [comment]
Yes, unfortunately. However, what is the alternative? To cater to non-conforming systems, and that removes pressure from implementors. To me, it seems more beneficial to encourage strong adherence to the ISO standard (which requires support for `chars`!), at least in the long term. It is a personal preference though, and this is the reason why in `format.pl`, I would like to encourage systems with strong support of the standard, and to encourage others to improve their support for standard features.

**Comment by pmoura** [comment]
I understand and sympathize with your view. But you're not only require support for `chars`. You're effectively forcing the use of `chars` even if the flag supports the other standard settings.

**Comment by triska** [comment]
Yes, that is a valid criticism. To use `library(format)`, you must use `chars`.

The reason for this is that I want to encourage the use of characters throughout in applications. Yes, it means that applications may have to be changed if they want to use this library. The good news, as I see it, is that this is the last time ever that such a change needs to be made. If not now, when?

**Comment by pmoura** [comment]
Is the `double_quotes` flag **local** to a module in either Tau Prolog or Scryer Prolog (the two systems where you contributed your library)? Otherwise, you are forcing a setting of `chars` globally for any program that happens to call the `format/2-3` predicates. As I suggested, supporting an atom on the first argument provides a pragmatic solution that doesn't hinder your goal in moving systems forward.

**Comment by triska** [comment]
In Scryer Prolog, the flag is **global**. Yes, this is the point: With the libraries I contribute, I am forcing `chars` globally in the sense that if you want to use them, then you have to set `double_quotes` to `chars` in Scryer. Or rather, you do not have to do anything, because `chars` is already the default value for this flag in Scryer, and also in Tau Prolog. 

The entire library architecture in Scryer will be catered towards characters, therefore Scryer for example has `chars_utf8bytes/2`, but *not* `codes_utf8bytes/2`.

To encourage and enforce lists of characters, I am not supporting alternative representations in the libraries I contribute, and I hope other systems will also adopt this strategy to encourage a convenient environment for reasoning about text.

**Comment by jariazavalverde** [comment]
The default value for `double_quotes` in Tau Prolog is `codes`. The ISO/IEC 13211-1 leaves the default value to the implementation, so I relied on the default value of SWI (that now is `string`) and GNU Prolog. But the decision was totally arbitrary, I would have no problem changing it.

**Comment by triska** [comment]
Ah I see: The last time I tried Tau Prolog, you had set `double_quotes` explicitly to `chars`, I forgot that you changed it specifically in that example.

Yes, if you would consider changing it, I think that would be one of the greatest and most beneficial long-term improvements you could make to the system. It would also make future exchange of libraries between Scryer and Tau much easier.

It is *so* convenient to write:

<pre>
<b>?- append("abc", "def", Ls).</b>
   Ls = "abcdef".
</pre>

This makes Prolog much easier to learn and teach, and is also great for programmers whose native scripts have very large code points, and where using `codes` makes answers especially unreadable.

**Comment by jariazavalverde** [comment]
Yes, I also think it's more natural to see a string as a list of characters. Big Haskell fan!

**Comment by triska** [comment]
This is the most futuristic commit I have seen in a while. Thank you a lot!

**Comment by jariazavalverde** [comment]
Added. Thank you very much to both!

**Comment by pmoura** [comment]
Thanks. It should be possible now to load and startup Logtalk. I just pushed an update adapter file to the Logtalk git repo. Is there a way to generate a `tau-prolog.js` from the current git version that includes all the modules?

**Comment by jariazavalverde** [comment]
I think the best option is to create a new project with npm (`npm init`), install the latest version of Tau Prolog in that project (`npm install tau-prolog`), and replace the files in `node_modules/tau-prolog`.

Then you should be able to import Tau Prolog and its modules in the following way:

```javascript
var pl = require("tau-prolog");
require("tau-prolog/modules/os")(pl);
require("tau-prolog/modules/lists")(pl);
require("tau-prolog/modules/random")(pl);
require("tau-prolog/modules/format")(pl);
require("tau-prolog/modules/statistics")(pl);
```

Note that there may be problems in the new version v0.3.0 due to the new module system, since I am still working on it.
