### ISSUE TITLE
random library set seed and get seed predicates

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#143]
Please consider adding to `library(random)` predicates to get and set the random generator seed (interpreted as a valid but otherwise opaque term). These predicates are key for e.g. property-based testing.

**Comment by jariazavalverde** [comment]
Added the following predicates to `random` module:

* `set_seed/1`
* `get_seed/1`
* `randomize/0`

Similar to [GNU Prolog interface](http://www.gprolog.org/manual/html_node/gprolog049.html).

**Comment by triska** [comment]
`randomize/0` is not a good idea because it makes predicates non-relational. A logic program  that uses random numbers should always use `set_seed/1` to make relational reasoning possible.

**Comment by jariazavalverde** [comment]
@triska It can be easily implemented by the user with `get_time/1` and `set_seed/1`:

```prolog
randomize :-
    get_time(Time),
    Seed is round(Time),
    set_seed(Seed).
```

**Comment by triska** [comment]
Yes, this is another good reason to leave it out of the library: Users who absolutely need `randomize/0` can easily implement it with the other available predicates, and it is better not to use it at all in order to ensure desirable relational properties of Prolog code.

The more problematic constructs are in the library, the more problematic user code will become too, making it harder and harder to reason about it in a way that realizes the full potential of a logic programming language.

In my personal view, these are quite strong indications for removing this predicate from the library. Having more predicates available in the library may seem an advantage at first. However, in the long run, it can deteriorate application code significantly, especially with predicates that require reasoning about implicit&nbsp;states. If these are used in actual application code, it makes debugging a nightmare, because a bug may arise only occasionally, and running the exact some query again may not reproduce the problem, or may reproduce a different, unrelated problem.

Deciding what to include and what to omit from the system libraries is certainly a very hard task for implementors due to the social pressure: We all have our favourite predicates we would like to see included in a system, at least I certainly do. I am grateful for conservative implementors who require careful reflection about what is truly essential, and what will eventually only hold us back.
