### ISSUE TITLE
Integer terms cannot be read (reading stalls?)

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#155]
For example:

```
read(T).
12.
```

Pressing return several times doesn't get us the binding for `T`; we need to enter another term. E.g.

```
read(T).
12.



a.

T = 12.

false.
$
```

Maybe a regression introduced by the recent fix to parse floats? In fact, entering a float works as expected which suggests that the parser is stalling after reading the `.`expecting it to signal a float instead of the end of the input.

**Comment by jariazavalverde** [comment]
This is due to the Node.js library that I use to read lines ([readline-sync](https://www.npmjs.com/package/readline-sync)). By default, it was removing the leading and trailing white spaces from the input text.

Probably, in the future, I will try to remove this library from the project. But for now this should fix the issue.

**Comment by pmoura** [comment]
This fix introduced a regression. Using the nice REPL in #154, if I call `read/1` before trying to compile some Logtalk files, the compilation fails. For example:

```bash
?- read(T).
a.
T = a.
false.
?- {basic_types(loader)}.
false.
```

If trying to compile and load the same files is the first thing after startup, it works (up to a point; there's an apparently unrelated bug where `resd_term/3` fails to parse a file term; I will create a separate issue):

```bash
?- {basic_types(loader)}.
% [ (/)Users(/)pmoura(/)logtalk(/)library(/)types(/)termp.lgt loaded ]
...
```
