### ISSUE TITLE
What browsers are supported? (DOM library)

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#170]
I am having problems running the little dog example in
SeaMonkey 2.53.2 . There is a key focus problem:

On Chrome Google it works fine, I can click into the dog
canvas, and use the keys:

![Unbenannt](https://user-images.githubusercontent.com/5411487/85293030-0f6eb480-b49d-11ea-931b-c592506a7b81.PNG)

In SeaMoney key strokes end in the search bar:

![seamonkey](https://user-images.githubusercontent.com/5411487/85293205-5066c900-b49d-11ea-8604-3291a0419547.gif)

**Comment by jariazavalverde** [comment]
The example also works fine in SeaMonkey. The problem is that in that browser the keys used to move the doge are also used to scroll the page. I just added to the example a call to the [prevent_default/1](http://tau-prolog.org/documentation/prolog/dom/prevent_default/1) predicate to prevent the default behavior. Now you should be able to run it without any problem.

**Comment by jburse** [comment]
There is still small error somewhere. I can also move around the
dog if I press ⌘s, ⌘w, etc..  So I guess the property is not yet filtered:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by jburse** [comment]
There is still small error somewhere. I can also move around the
dog if I press ⌘s, ⌘w, etc..  So I guess the property is not yet filtered:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

This happens also in Chrome, not only in Seamonkey. But you
need to test on a mac.
