### ISSUE TITLE
tau prolog run in  nodejs  have some  problem  

### ISSUE THREAD

**Issue by anabapy** [tau-prolog/tau-prolog#219]
var pl = require("./modules/core");
require("./modules/lists")(pl);
var session = pl.create(1000);

var program = `
                :- use_module(library(lists)).
		append([1, 2, 3], [a, b, c], [1, 2, 3, a, b, c]).
		append([1, 2, 3], [a, b, c], [c, a, k, e]).
		`
// Goal
var goal = "append([1, 12, 3], [a, b, c], X).";
// Load the program
session.consult(program , {
	success: function() {
		// Query the goal
		session.query(goal, {
			success: function() {
				// Look for answers
				session.answers(x => console.log(pl.format_answer(x)));
			}
		});
	}
});

//  result : false.

**Comment by jariazavalverde** [comment]
The problem is that you define your own version of `append/3` in the `user` module with these two clauses:

```prolog
append([1, 2, 3], [a, b, c], [1, 2, 3, a, b, c]).
append([1, 2, 3], [a, b, c], [c, a, k, e]).
```

So when you call `append/3` the system finds a definition in the `user` module, and does not use the one in the `lists` module. You have to remove those two clauses from your program, or call the goal with the context `lists:append([1, 12, 3], [a, b, c], X).`.

**Comment by anabapy** [comment]
ok,it's no problem.
