### ISSUE TITLE
permission error when using clause/2 in sandbox

### ISSUE THREAD

**Issue by JeanChristopheRohner** [tau-prolog/tau-prolog#227]
In the [sandbox](http://tau-prolog.org/sandbox/) i have:
```
mortal(X):-human(X).
human(josh).
test(H, B):-clause(H, B).
```
With the goal `test(mortal(josh), B).`

I get the error `uncaught exception: error(permission_error(access,private_procedure,mortal/1),clause/2)`

Not sure what the problem is.

**Comment by triska** [comment]
This is because the standard prescribes:

<pre>
<b>7.5.3 Private and public procedures</b>

...

Each built-in predicate and control construct shall be private, 
<b>and a static user-defined procedure shall be private by default.</b>

A clause of a public procedure can be inspected, a clause of 
a private procedure cannot be inspected.
</pre>

Thus, to make this work, declare the predicates you want to inspect as *dynamic*, using the `dynamic/1` directive&nbsp;(7.4.2.1):

<pre>
:- dynamic(mortal/1).
</pre>

**Comment by JeanChristopheRohner** [comment]
Thanks for the explanation @triska (I am used to SWI Prolog and SWISH where this isn't needed).

**Comment by triska** [comment]
Yes this is a major attraction of a system like Tau Prolog which aims for strict conformance to the ISO&nbsp;standard: It makes sure that your code remains portable to other systems at least in many important respects!
