### ISSUE TITLE
existence_error in node.js example

### ISSUE THREAD

**Issue by jandrieu** [tau-prolog/tau-prolog#246]
Testing out the node.js example at http://tau-prolog.org/manual/compatibility-with-nodejs gave me the following error (with analyzer.js as my node.js executable)
```bash
 ./analyze.js bread
uncaught exception: error(existence_error(procedure,/(item,2)),/(top_level,0))
false.
```
However, the example says that I should get back something like 
```
$ ./analyze.js bread
ItemID = 1, ShopID = 1, Price = 0.33, Shop = tau ;
false.
```

When I tried this in the online sandbox, it worked fine.
```bash
ItemID = 1, ShopID = 1, Price = 0.33, Shop = tau.
parsing query: item(id(ItemID),name(bread)),stock(item(ItemID),shop(ShopID),_,price(Price)),shop(id(ShopID),name(Shop),_) ok!
```

Any ideas about how to get this working?

**Comment by jariazavalverde** [comment]
Hi Joe.

We have not yet adapted all the documentation and examples to the new interface. Please, check the changes to the `consult` and `query` methods in version 0.3.0:

https://github.com/tau-prolog/tau-prolog/blob/master/RELEASE_NOTES.md#version-030---august-31-2020

Soon we'll also add an interface to work with promises instead of callbacks.

**Comment by jariazavalverde** [comment]
We've already adapted all the examples in the manual to the new interface.
