### ISSUE TITLE
Number overflow not recognized

### ISSUE THREAD

**Issue by ghost** [tau-prolog/tau-prolog#262]
Was testing with TauProlog 0.3.1 (beta)
```
?- number_chars(X,"30000000000000000000000000").
X = 3.
?- X is 30000000000000000000000000.
X = 3.
```
Was rather expecting an overflow error, because of the flag value:
```
?- current_prolog_flag(bounded, X).
X = true
```

**Comment by jariazavalverde** [comment]
The problem is that JavaScript converts integers with more than 21 digits to scientific notation when used in a string context, and the [parseInt](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/parseInt) function stops parsing on the letter `e`. Not really an overflow issue (although `300000000000000000000001234`, for example, may not be accurately represented).

I've just uploaded a temporary workaround while I look at other options.

![imagen](https://user-images.githubusercontent.com/5055295/152609816-0c1ccc2c-a749-4191-9dde-c5a417a2454d.png)

Another problem is that large integers are currently being represented textually as floats, but at least now it is possible to check that the number exceeds the maximum safe integer in JavaScript and throw the exception.

Thanks for the report.
