### ISSUE TITLE
Feature request non-blocking sandbox, ev. needs yielding engine

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#291]
TauProlog has a new interfaces:

> promiseQuery: queries a goal and returns a promise that is resolved 
when the goal loads successfully, or rejected when there is an error. It 
takes the same arguments as the query method.
http://tau-prolog.org/manual/promises-interface

The test case was a large limit and then:
```
longrunning :- 
    between(1,300,_),
    between(1,300,_),
    between(1,300,_),
    fail.
longrunning.
```
But I find that this sandbox here is blocking:

![Unbenannt](https://user-images.githubusercontent.com/95891213/152998836-89a6f59d-37b5-4919-b497-a2a86ef1af02.PNG)

http://tau-prolog.org/sandbox/

Is there another sandbox already online?

**Comment by Jean-Luc-Picard-2021** [comment]
I have set-up an according sandbox for Doglog player, the 
Audio Example uses such a sandbox. The Audio Example will 
disable the Tryit button and enable it again, when finished.

But its non-blocking, you can interact with the browser,
and it will not show the warning display in Chrome. Unfortunately
there is still an unsolved problem, the LIPS go down:

http://www.xlog.ch/izytab/doclet/docs/18_live/10_reference/example03/package.html
![Unbenannt3](https://user-images.githubusercontent.com/95891213/153001331-35cc0536-0041-4de1-9a1b-43683435b3d8.PNG)

**Comment by Jean-Luc-Picard-2021** [comment]
Possibly not a feasible solution. Because sleep(0) is capped
by 4ms in the browser, so if you call it too often, you quite a slow
down. Or do you have another implementation of sleep/1

that doesn't call setTimeout() ? The capping is official:

https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers

**Comment by Jean-Luc-Picard-2021** [comment]
According to [uncatalogued](https://github.com/tau-prolog/tau-prolog/issues/292) entry sleep/1, it indeed calls setTimeout().
This would even not work on node.js, because node.js does also
cap setTimeout(), not by 4ms, but by 1ms.

On node.js you need to brach into setImmediate() when the
given delay is zero. setImmediate() is more complicated in the
browser, there exist some polyfil suggestions though.

**Comment by jariazavalverde** [comment]
The Tau Prolog sandbox is just that, a sandbox, and it allows you to set an inference limit to prevent the browser from freezing. It is built using the 3 main methods of Tau Prolog: `consult`, `query` and `answer`.

http://tau-prolog.org/manual/a-simple-tutorial

You can set up a sandbox that runs a query with a limit of, say, 1000 inferences. If the limit of inferences is reached, in the callback of the `answer` method, you can make it continue looking for the answer. That way the interpreter can stop working automatically from time to time, so that the browser takes care of the rest of the events. 

In our current sandbox, when the query stops the user has to explicitly request that the search continue, requesting another answer. But this behavior can be changed by modifying the callback. 

![imagen](https://user-images.githubusercontent.com/5055295/153061590-1bf041f3-86c1-4aa0-b5b9-41a5cb5db8fb.png)

Regarding `sleep/1` predicate, every time you stop the execution so that the browser processes the rest of the events, whatever way it is, there may be a delay. Precisely because you stop for other events to be processed. JavaScript is single-thread, and this is just a negative effect of its concurrency model. In any case, both with `sleep/1` predicate or with the inference limit, the user can choose how often to stop the execution.

**Comment by Jean-Luc-Picard-2021** [comment]
Thats not what Erlang did. In Erlang there was a counter and
long running actors where automatically yielded. You can
lookup the Erlang documentation.

**Comment by Jean-Luc-Picard-2021** [comment]
Whats so difficult in providing a yielding engine?

**Comment by Jean-Luc-Picard-2021** [comment]
How do your answers respond to my question:
> Is there another sandbox already online?
