### ISSUE TITLE
string_to_list missing

### ISSUE THREAD

**Issue by flipflop133** [tau-prolog/tau-prolog#303]
I noticed that the predicate [string_to_list](https://www.swi-prolog.org/pldoc/doc_for?object=backward_compatibility%3Astring_to_list/2)  wasn't implemented, so I wonder if there is another way to iterate over a string to manipulate it.
My use case is implementing a split function similar to the one present in Python.

**Comment by triska** [comment]
In Tau Prolog, a string is a list. Example:

<pre>
<b>?- is_list("abc").</b>
true.
</pre>

There is therefore no need for this predicate in Tau Prolog, you can use the string directly as a list.

**Comment by flipflop133** [comment]
Thank you for your quick answer, though this is a nice way to handle strings, the issue is compatibility with pure prolog or other tools like pyswip. What is the logic I'm missing in this?

**Comment by triska** [comment]
SWI-Prolog violates the Prolog ISO standard in its handling of strings, which are a proprietary atomic data&nbsp;type in this system. Please see the following document for more information:

https://www.complang.tuwien.ac.at/ulrich/iso-prolog/SWI7_and_ISO

All Prolog systems that have become available in the last 5 years treat strings as lists of characters:

- [ichiban/prolog](https://github.com/ichiban/prolog)
- [Scryer Prolog](https://github.com/mthom/scryer-prolog)
- [Tau Prolog](https://github.com/tau-prolog/)
- [Trealla Prolog](https://github.com/trealla-prolog/trealla)

Scryer Prolog has shown that lists of characters can be implemented very efficiently, and from this point on, it is clear that all future Prolog systems will have to implement the same representation in order to be competitive with Scryer Prolog for convenient text processing. The best case scenario is for SWI-Prolog to adopt the same representation. This was proposed to the SWI implementor about 8 years ago, and rejected in favour of a non-conforming extension that only SWI-Prolog implements, making SWI-Prolog a highly idiosyncratic system that is incompatible with all other Prolog systems by default. For compatibility with other systems, I recommend to use a system that adheres to the Prolog ISO&nbsp;standard at least in such a critical aspect as string handling, which is a really fundamental feature of Prolog.

**Comment by flipflop133** [comment]
Thanks a lot for all these high quality explainations! I'm doing a university project but we started using pyswip (without knowing SWI weren't respecting the ISO) and so we decided to stick as we didn't wanted to convert our current code base to not lose time. This scenario is exactly what you described, SWI should respect the ISO to avoid this kind of scenario.
Knowing all this we would have started with TAU directly.
